title: kinetic-cme
description: A description to the kinetic-cme code!
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "dark"

footer:
  links:
    - label: "GitLab"
      icon: "fab fa-fw fa-square-gitlab"
      url: "https://git.uibk.ac.at/c7021158/kinetic-cme/-/tree/main?ref_type=heads"

atom_feed:
  hide: true

search: true